-- ============================================================================
-- 007_pelaku_usaha_bank_reporting.sql
--
-- Adds Pelaku Usaha waste-management reporting and Bank Sampah reporting.
-- This migration documents schema changes that were originally applied
-- directly to the remote Supabase project.
-- ============================================================================


-- ============================================================================
-- 1. PROFILES: add Pelaku Usaha role
-- ============================================================================

alter table public.profiles
  drop constraint if exists profiles_role_check;

alter table public.profiles
  add constraint profiles_role_check
  check (
    role in (
      'warga',
      'petugas',
      'bank',
      'admin',
      'superadmin',
      'pelaku_usaha'
    )
  );

create policy "profiles_insert_self_pelaku_usaha"
on public.profiles
for insert
to authenticated
with check (
  id = (auth.jwt() ->> 'sub')
  and role = 'pelaku_usaha'
);


-- ============================================================================
-- 2. PELAKU USAHA
-- ============================================================================

create table public.pelaku_usaha (
  id uuid primary key default gen_random_uuid(),

  profile_id text not null unique
    references public.profiles(id)
    on delete cascade,

  nama_usaha text not null,

  jenis_usaha text not null
    check (
      jenis_usaha in (
        'BUMDes',
        'PT',
        'Sekolah',
        'Hotel',
        'Perkantoran',
        'Lainnya'
      )
    ),

  alamat text,
  wilayah text,

  created_at timestamptz not null default now()
);

alter table public.pelaku_usaha enable row level security;


create policy "pelaku_usaha_insert_own"
on public.pelaku_usaha
for insert
to authenticated
with check (
  profile_id = (auth.jwt() ->> 'sub')
);


create policy "pelaku_usaha_select_own"
on public.pelaku_usaha
for select
to authenticated
using (
  profile_id = (auth.jwt() ->> 'sub')
);


create policy "pelaku_usaha_update_own"
on public.pelaku_usaha
for update
to authenticated
using (
  profile_id = (auth.jwt() ->> 'sub')
)
with check (
  profile_id = (auth.jwt() ->> 'sub')
);


create policy "pelaku_usaha_select_admin"
on public.pelaku_usaha
for select
to authenticated
using (
  current_role_is('admin')
  or current_role_is('superadmin')
);


-- ============================================================================
-- 3. PELAKU USAHA — WASTE MANAGEMENT RECORDS
-- ============================================================================

create table public.waste_management_records (
  id uuid primary key default gen_random_uuid(),

  pelaku_usaha_id uuid not null
    references public.pelaku_usaha(id)
    on delete cascade,

  tanggal date not null,

  created_at timestamptz not null default now()
);

alter table public.waste_management_records enable row level security;


create policy "waste_records_insert_own"
on public.waste_management_records
for insert
to authenticated
with check (
  exists (
    select 1
    from public.pelaku_usaha pu
    where pu.id = waste_management_records.pelaku_usaha_id
      and pu.profile_id = (auth.jwt() ->> 'sub')
  )
);


create policy "waste_records_select_own"
on public.waste_management_records
for select
to authenticated
using (
  exists (
    select 1
    from public.pelaku_usaha pu
    where pu.id = waste_management_records.pelaku_usaha_id
      and pu.profile_id = (auth.jwt() ->> 'sub')
  )
);


create policy "waste_records_select_admin"
on public.waste_management_records
for select
to authenticated
using (
  current_role_is('admin')
  or current_role_is('superadmin')
);


-- ============================================================================
-- 4. PELAKU USAHA — WASTE MANAGEMENT DETAILS
-- ============================================================================

create table public.waste_management_details (
  id bigint generated by default as identity primary key,

  record_id uuid not null
    references public.waste_management_records(id)
    on delete cascade,

  category text not null
    check (
      category in (
        'Sisa bahan penyiapan makanan',
        'Sisa makanan',
        'Kertas/Karton',
        'Plastik',
        'Kaca',
        'Kain',
        'Karet',
        'Residu',
        'B3'
      )
    ),

  handled_kg numeric not null default 0
    check (handled_kg >= 0),

  unhandled_kg numeric not null default 0
    check (unhandled_kg >= 0),

  unique (record_id, category)
);

alter table public.waste_management_details enable row level security;


create policy "waste_details_insert_own"
on public.waste_management_details
for insert
to authenticated
with check (
  exists (
    select 1
    from public.waste_management_records r
    join public.pelaku_usaha pu
      on pu.id = r.pelaku_usaha_id
    where r.id = waste_management_details.record_id
      and pu.profile_id = (auth.jwt() ->> 'sub')
  )
);


create policy "waste_details_select_own"
on public.waste_management_details
for select
to authenticated
using (
  exists (
    select 1
    from public.waste_management_records r
    join public.pelaku_usaha pu
      on pu.id = r.pelaku_usaha_id
    where r.id = waste_management_details.record_id
      and pu.profile_id = (auth.jwt() ->> 'sub')
  )
);


create policy "waste_details_select_admin"
on public.waste_management_details
for select
to authenticated
using (
  current_role_is('admin')
  or current_role_is('superadmin')
);


-- ============================================================================
-- 5. LEGACY BANK SAMPAH REPORTING
--
-- Kept because these tables currently exist in the remote database.
-- The active Bank Sampah reporting flow now uses bank_manual_records.
-- ============================================================================

create table public.bank_waste_records (
  id uuid primary key default gen_random_uuid(),

  bank_unit_id uuid not null
    references public.bank_units(id)
    on delete cascade,

  tanggal date not null,

  created_at timestamptz not null default now()
);

alter table public.bank_waste_records enable row level security;


create policy "bank_waste_records_insert_own"
on public.bank_waste_records
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = (auth.jwt() ->> 'sub')
      and p.role = 'bank'
      and p.bank_unit_id = bank_waste_records.bank_unit_id
  )
);


create policy "bank_waste_records_select_own"
on public.bank_waste_records
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = (auth.jwt() ->> 'sub')
      and p.role = 'bank'
      and p.bank_unit_id = bank_waste_records.bank_unit_id
  )
);


create policy "bank_waste_records_select_admin"
on public.bank_waste_records
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = (auth.jwt() ->> 'sub')
      and p.role in ('admin', 'superadmin')
  )
);


-- ============================================================================
-- 6. LEGACY BANK SAMPAH DETAILS
-- ============================================================================

create table public.bank_waste_details (
  id bigint generated by default as identity primary key,

  record_id uuid not null
    references public.bank_waste_records(id)
    on delete cascade,

  category text not null
    check (
      category in (
        'Sisa bahan penyiapan makanan',
        'Sisa makanan',
        'Kertas/Karton',
        'Plastik',
        'Kaca',
        'Kain',
        'Karet',
        'Residu',
        'B3'
      )
    ),

  handled_kg numeric not null default 0
    check (handled_kg >= 0),

  unhandled_kg numeric not null default 0
    check (unhandled_kg >= 0),

  economic_value numeric not null default 0
    check (economic_value >= 0),

  unique (record_id, category)
);

alter table public.bank_waste_details enable row level security;


create policy "bank_waste_details_insert_own"
on public.bank_waste_details
for insert
to authenticated
with check (
  exists (
    select 1
    from public.bank_waste_records r
    join public.profiles p
      on p.bank_unit_id = r.bank_unit_id
    where r.id = bank_waste_details.record_id
      and p.id = (auth.jwt() ->> 'sub')
      and p.role = 'bank'
  )
);


create policy "bank_waste_details_select_own"
on public.bank_waste_details
for select
to authenticated
using (
  exists (
    select 1
    from public.bank_waste_records r
    join public.profiles p
      on p.bank_unit_id = r.bank_unit_id
    where r.id = bank_waste_details.record_id
      and p.id = (auth.jwt() ->> 'sub')
      and p.role = 'bank'
  )
);


create policy "bank_waste_details_select_admin"
on public.bank_waste_details
for select
to authenticated
using (
  exists (
    select 1
    from public.bank_waste_records r
    where r.id = bank_waste_details.record_id
  )
  and exists (
    select 1
    from public.profiles p
    where p.id = (auth.jwt() ->> 'sub')
      and p.role in ('admin', 'superadmin')
  )
);


-- ============================================================================
-- 7. ACTIVE BANK SAMPAH MANUAL REPORTING
-- ============================================================================

create table public.bank_manual_records (
  id uuid primary key default gen_random_uuid(),

  bank_unit_id uuid not null
    references public.bank_units(id)
    on delete cascade,

  tanggal date not null,

  category text not null
    check (
      category in (
        'Organik',
        'Plastik PET',
        'Kertas',
        'Botol & kaca',
        'Logam',
        'Sampah lainnya'
      )
    ),

  weight_kg numeric not null default 0
    check (weight_kg >= 0),

  price numeric not null default 0
    check (price >= 0),

  deposit_amount numeric not null default 0
    check (deposit_amount >= 0),

  withdrawal_amount numeric not null default 0
    check (withdrawal_amount >= 0),

  balance numeric not null default 0
    check (balance >= 0),

  officer text not null,

  created_at timestamptz not null default now()
);

alter table public.bank_manual_records enable row level security;


create policy "bank_manual_records_insert_own"
on public.bank_manual_records
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = (auth.jwt() ->> 'sub')
      and p.role = 'bank'
      and p.bank_unit_id = bank_manual_records.bank_unit_id
  )
);


create policy "bank_manual_records_select_own"
on public.bank_manual_records
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = (auth.jwt() ->> 'sub')
      and p.role = 'bank'
      and p.bank_unit_id = bank_manual_records.bank_unit_id
  )
);


create policy "bank_manual_records_select_admin"
on public.bank_manual_records
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = (auth.jwt() ->> 'sub')
      and p.role in ('admin', 'superadmin')
  )
);